version: "3.8"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - PGTZ=Asia/Seoul
    ports:
      - 15001:5432
    volumes:
      - /home/swook/share/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 1s
      retries: 5
